# Q1



In [2]:
#1 
list1 = [1,5,6,2,3,10,11,21,50]     # a list of numbers 

#prints maxiimum from the list1
max(list1)                          


50

# Q2

In [131]:
#2
str_list = ['New York', 'Seattle', 'Virginia','Maryland', 'Texas','Utah']

# Use join() to concatenate the list of strings with a comma separator.join(name)
combined_string = ", ".join(str_list)

# Output the result
print(combined_string)


New York, Seattle, Virginia, Maryland, Texas, Utah


['New York', 'Seattle', 'Virginia', 'Maryland', 'Texas', 'Utah']

# Q3

In [132]:
#3

#Create a dictionary with keys name and age and values Dev and 23 coresspondingly.
dict_ = {
    'name' : 'Dev',
    'age'  : 23
}


In [133]:
print(dict_['age']) 

23


## Q4

In [136]:
#4

list4 = [1,2,3,4,5,6,7,8,5,4,3,2,1]  #List including some duplicate values

# Initialize an empty list to store the unique elements
unique_list = []

# Iterate through the original list
for i in list4:
    # Only add the item to unique_list if it hasn't been added before
    if i not in unique_list:
        unique_list.append(i)

# Output the result
print(unique_list)

[1, 2, 3, 4, 5, 6, 7, 8]


# Q5

In [137]:
#5
#Import numpy  as np

import numpy as np

nparray = np.array([1,2,3,4,5,6])  # Sample NumPy array

sum(nparray) #calculate sum of all elements in the array


21

## Q6

In [145]:
#6

#create 2D array using np.array 
nparray2 =np.array ([[2,4,6,8,10],
                     [1,3,5,7,31]])


# Calculate the maximum values for each column
max_values = np.max(nparray2, axis=0)

# Output the result
print(max_values)

[ 2  4  6  8 31]


## Q7

In [146]:
import pandas as pd 

# Sample DataFrame
data = {
    'Name': ['Alex','Sam', 'Carol', 'Meghan', 'Chris', 'Tom', 'John'],
    'Age' : [23, 30, 22, 25, 60, 45, 19]
}

df = pd.DataFrame(data)


In [147]:
df_sorted = df.sort_values(by = 'Age', ascending = False) # Sort the DataFrame by the "Age" column in descending order


In [148]:
print(df_sorted)

     Name  Age
4   Chris   60
5     Tom   45
1     Sam   30
3  Meghan   25
0    Alex   23
2   Carol   22
6    John   19


## Q8

In [45]:
#8

#sample of dataframe
data2= {
    'Name' : ['Alex','Sam', 'Carol', 'Meghan', 'Chris', 'Tom', 'John'],
    'Age'  : [23, 30, 22, 25, 60, 45, 19],
    'Sales': [200, 300, 400, 800, 900, 1000, 100]
}

df2 = pd.DataFrame(data2) #convert data into dataframe

In [48]:
total_sales = df2['Sales'].sum()  #find the sum of sales column
print(total_sales)

3700


### Q9

In [52]:
#9
var1 = 333             #assigning integer as var1
var2 = 'Angdembay'     #assigning string as var2

print(type(var1))  #checks the class of variables 
print(type(var2))



<class 'int'>
<class 'str'>


## Q10

In [56]:
#10

# sample of mix list
mix_list = [2, 3, 1.2, 4.1, 33, 3.3, 'Apple', 'Orange', 4.5, 'Lemon', 'Cherry']

integer_ = []   # Initialize an empty list to store the integer
float_ =[]      # Initialize an empty list to store the float
string_ = []    # Initialize an empty list to store the string

#Iterate through the mixed list
for i in mix_list:
    if type(i) == int:
        integer_.append(i) # append integer into integer list
    elif type(i) == float:
        float_.append(i)   #append float type into float list
    else:
        string_.append(i)  #append string type to string
        

In [59]:
#print the seperate lists of each type 
print('Integers =', integer_)
print('Floats = ', float_)
print('Strings =', string_)

Integers = [2, 3, 33]
Floats =  [1.2, 4.1, 3.3, 4.5]
Strings = ['Apple', 'Orange', 'Lemon', 'Cherry']


## Q11

In [64]:
#11.
#sample of string of comma seoareted numbers
num_str = "22, 34, 1, 2, 5, 21"

num_list = [int(num) for num in num_list] #Convert each substring to an integer

print(num_list)





[22, 34, 1, 2, 5, 21]


## Q12

In [89]:
#12.

#sample of a sentence
sentence = 'My name is Rista Angdembay'

# Step 1: Split the sentence into words
words = sentence.split()
words

#reverse each word stored in words 
reversed_words = [word[::-1] for word in words]

# join the words to make a rentence with a space " " between the reversed words
reversed_sentence = " ".join(reversed_words)

# Output the result
print(reversed_sentence)

yM eman si atsiR yabmedgnA


## Q13

In [91]:
#13.

#samples of two lists 
list1 = ['Name','Age','ZipCode']
list2 = ['Andra', 27, '11373']

# Ensure both lists are of the same length
if len(list1) == len(list2) :  
    dict_ = {list1[i]: list2[i] for i in range(len(list1))} # Use dictionary comprehension to create the dictionary
else:
    # Handle the case where lists are not of the same length
    raise ValueError("Both lists must have the same length.")

# Output the result
print(dict_)

{'Name': 'Andra', 'Age': 27, 'ZipCode': '11373'}


## Q14

In [99]:
#14.

tuples = [('Alisha', 33), ('John', 19), ('Sara', 50), ('Jimmy', 16), ('Jesenia',50)]

tuples.sort( key = lambda x : x[1]) # Sort by the second element in each tuple (age)

# Output the sorted list
print(tuples)

[('Jimmy', 16), ('John', 19), ('Alisha', 33), ('Sara', 50), ('Jesenia', 50)]


## Q15

In [103]:
#15.

array1 = np.array([[3,5,7,9,10],
                   [56,34,33,40,44]])

row_means = np.mean(array1, axis=1)

# Output the result
print(row_means)

[ 6.8 41.4]


## Q16

In [104]:
#16.

array2 = np.zeros(10) #creating an array conataining 10 zeroes
array2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
array2[5]= 5  #assigning 5 to the fifth element of the array
print(array2)

[0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]


## Q17

In [113]:
#17
import pandas as pd 

data = {
    'Name':["Alice", "Bob", "Charlie", "David", "Eve"],
    'Scores':[99, 95, 110, 85, 100]
}

dataframe = pd.DataFrame(data)

In [115]:
dataframe['Scores'].median() #median of the scores 

91.0

## Q18

In [117]:
#18.
import pandas as pd 

# Sample DataFrame
data = {
    "Date": ["2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04", "2024-01-05"],
    "Sales": [150, 90, 200, 120, 80]
}

df = pd.DataFrame(data)

# Convert the "Date" column to datetime format if it's not already
df["Date"] = pd.to_datetime(df["Date"])



In [118]:
# Step 1: Filter rows where "Sales" is above 100
filtered_df = df[df["Sales"] > 100]

# Step 2: Sort the filtered DataFrame by "Date" in descending order
sorted_df = filtered_df.sort_values(by="Date", ascending=False)

# Output the result
print(sorted_df)

        Date  Sales
3 2024-01-04    120
2 2024-01-03    200
0 2024-01-01    150


## Q19

In [124]:
#19.

number_str = "we"  # assigning a number as a string with enclosed with " "

if number_str.isdigit():  #checks if it is a digit 
    number = int(number_str) #converts into integer types 
    print(f"{number}")  #  prints out the converted integer
else:
    print("Invalid case.") # itv prints out if not number_str in not a digit



Invalid case.


## Q20

In [122]:
#20

# Create a mixed list
mix_list = [2, 3, 1.2, 4.1, 33, 3.3, 'Apple', 'Orange', 4.5, 'Lemon', 'Cherry']


string_list = [i for i in mix_list if type(i) == str] # Extract all strings using list comprehension with type()

print(string_list) #print the list of string

['Apple', 'Orange', 'Lemon', 'Cherry']
